import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import About from "../components/About";
import Features from "../components/Features";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-[90%] ml-[5%] pt-8 mb-8 flex flex-row justify-between items-center">
        <div className="w-52">
          <img src="/logo.png" className="w-[70%] aspect-auto" />
        </div>
        <div className="hidden sm:flex justify-between sm:w-[50%] md:w-[30%]">
          <Link href="/">Home</Link>
          <Link href="/">Contact</Link>
          <Link href="/">Blog</Link>
        </div>
      </header>
      <main className="w-[90%] ml-[5%]">
        <div className="flex flex-col md:flex-row">
          <div>
            <div className="text-white text-2xl bg-[#1C9BF1] w-4/5 md:w-2/4 py-2 px-4">
              Your One Stop Online
            </div>
            <div className="text-black text-2xl font-bold w-full md:w-2/4 py-2">
              Purchase Solution
            </div>
            <div className="text-black text-lg font-bold w-full mt-4 md:w-2/4 py-2">
              Get all you want in one place
            </div>
            <div className="w-full md:w-3/5 py-2">
              We provide 3 in 1 solution to your online retail and wholesale
              purchases as well as handymen services.
            </div>
          </div>
          <div className="h-48 md:h-full flex justify-center">
            <img src="/agacyPhone.png" className="h-full aspect-auto" />
          </div>
        </div>
        <About />
        <Features />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
